version: '3'

networks:
  backend:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./projects:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx/
    depends_on:
      - php-7.1
      - php-7.3
      - mysql-8
      - mysql-5.7
      - redis
      - mongo
      - postgres
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    container_name: redis
    volumes:
      - ./redis/data:/var/lib/redis
      - ./redis/conf:/usr/local/etc/redis/redis.conf
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - backend

  mysql-5.7:
    image: mysql:5.7
    container_name: mysql-5.7
    restart: unless-stopped
    volumes:
      - ./mysql-5.7/data:/var/lib/mysql
      - ./mysql-5.7/conf.d:/etc/mysql/conf.d
      - ./mysql-5.7/logs:/var/log/mysql/
      - ./mysql-5.7/dump:/dump
    ports:
      - "${MYSQL_5_7_PORT}:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - backend

  mysql-8:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password --skip_name_resolve
    container_name: mysql-8
    restart: unless-stopped
    volumes:
      - ./mysql-8/data:/var/lib/mysql
      - ./mysql-8/conf.d:/etc/mysql/conf.d
      - ./mysql-8/logs:/var/log/mysql/
      - ./mysql-8/dump:/dump
    ports:
      - "${MYSQL_8_PORT}:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - backend

  postgres:
    image: postgres:alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/dump:/dump
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
        - backend
    container_name: postgres

  mongo:
    image: mongo:4.2
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/configdb:/data/configdb
      - ./mongo/dump:/dump
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - backend
    container_name: mongo

  php-8.0:
    build:
      context: php-8-workspace
      dockerfile: Dockerfile
      args:
        DOCKER_PHP_VERSION: '8.0'
        TZ: ${WORKSPACE_TIMEZONE}
    working_dir: /var/www
    container_name: php-8.0
    volumes:
      - ./.ssh:/home/www-data/.ssh
      - ./projects:/var/www
      - ./php-ini/8.0/php.ini:/usr/local/etc/php/php.ini
      - ./php-workers/8.0/supervisor.d:/etc/supervisor.d
    ports:
      - "${PHP_8_0_PORT}:9000"
    networks:
      - backend
    extra_hosts:
      - 'project-1.localhost:192.168.65.2'
      - 'project-2.localhost:192.168.65.2'
      - 'project-3.localhost:192.168.65.2'

  php-7.3:
    build:
      context: php-7-workspace
      dockerfile: Dockerfile
      args:
        DOCKER_PHP_VERSION: '7.3'
        DOCKER_PHP_ENABLE_XDEBUG: ${DOCKER_PHP_ENABLE_XDEBUG}
        TZ: ${WORKSPACE_TIMEZONE}
    working_dir: /var/www
    container_name: php-7.3
    volumes:
      - ./.ssh:/home/www-data/.ssh
      - ./projects:/var/www
      - ./php-ini/7.3/php.ini:/usr/local/etc/php/php.ini
      - ./php-workers/7.3/supervisor.d:/etc/supervisor.d
    ports:
      - "${PHP_7_3_PORT}:9000"
    networks:
      - backend
    extra_hosts:
      - 'project-1.localhost:192.168.65.2'
      - 'project-2.localhost:192.168.65.2'
      - 'project-3.localhost:192.168.65.2'

  php-7.1:
    build:
      context: php-7-workspace
      dockerfile: Dockerfile
      args:
        DOCKER_PHP_VERSION: '7.1'
        DOCKER_PHP_ENABLE_XDEBUG: ${DOCKER_PHP_ENABLE_XDEBUG}
        TZ: ${WORKSPACE_TIMEZONE}
    working_dir: /var/www
    container_name: php-7.1
    volumes:
      - ./.ssh:/home/www-data/.ssh
      - ./projects:/var/www
      - ./php-ini/7.1/php.ini:/usr/local/etc/php/php.ini
      - ./php-workers/7.1/supervisor.d:/etc/supervisor.d
    ports:
      - "${PHP_7_1_PORT}:9000"
    networks:
      - backend
    extra_hosts:
      - 'project-1.localhost:192.168.65.2'
      - 'project-2.localhost:192.168.65.2'
      - 'project-3.localhost:192.168.65.2'